spring.application.name=EventosTech
spring.datasource.url=jdbc:postgresql://localhost:5432/eventos_tech
spring.datasource.username=queiroz
spring.datasource.password=aoq
aws.region=us-east-1
aws.bucket.name=eventostech-imagens
