spring.application.name=EventosTech
spring.datasource.url=jdbc:postgresql://localhost:5432/eventos_tech
spring.datasource.username=queiroz
spring.datasource.password=aoq
aws.region=us-east-1
aws.bucket.name=eventtech-img
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB